### ISSUE TITLE
fragment preview support

### ISSUE THREAD

**Issue by ffdead** [birkir/gatsby-source-prismic-graphql#10]
Is there a recommended way of defining GraphQL fragments so that the Apollo client knows about them?

Currently when I defined a fragment in a component like this:

```
export const query = graphql`
  fragment SiteSettings on PRISMIC_Site_settings {
    ...
  }
`
```

The preview throws this error:

```
index.js:2177 Failed to fetch preview Error: Network error: Response not successful: Received status code 500
    at new ApolloError (bundle.esm.js:60)
```

Response:
```
{"message":"Query does not pass validation. Violations:\n\nUnknown fragment 'SiteSettings'. (line 30, column 5):\n    ...SiteSettings\n    ^"}
```

So it seems as if the fragment is unknown at this point.

---
Sorry for the storm of new issues. We really hope to use this plugin on a project to enable the preview functionality. I'm reporting what I find and hope it helps someone in the future :)

**Comment by birkir** [comment]
We should be able to support fragments like the gatsby-source-graphql-universal https://github.com/birkir/gatsby-source-graphql-universal/blob/d743dad75cc9e47e6950e634c3fa8b9292d3e12d/src/index.js#L114

**Comment by birkir** [comment]
Fixed in ~2.3.3~ and 3.0.0

**Comment by ffdead** [comment]
Still not working with `v2.3.3`

Using a Fragment still generates an error with active Preview cookie:

` "Query does not pass validation. Violations:↵↵Unknown fragment 'MyTestFrag'. (line 3, column 5):↵    ...MyTestFrag↵    ^"`

This is the test code, which renders ok when not in Preview mode:

```jsx
import { graphql } from 'gatsby'

import GlobalHome from 'views/global-home/GlobalHome'

export const myFrag = graphql`
  fragment MyTestFrag on PRISMIC_Global_home {
    title
  }
`

export const query = graphql`
  query Home {
    prismic {
      global_home(uid: "home", lang: "en-us") {
        ... MyTestFrag
      }
    }
  }
`

GlobalHome.query = query

export default GlobalHome
```

**Comment by ffdead** [comment]
Confirmed it's working in `v3.0.0-alpha.21` using this syntax: https://github.com/birkir/gatsby-source-prismic-graphql#fragments

Good stuff!
