### ISSUE TITLE
Preview changes does't render changes on singleton page

### ISSUE THREAD

**Issue by nikita-seliverstov** [birkir/gatsby-source-prismic-graphql#167]
Hi, how does previews works with page queries? can't find information on that. Right now it redirects from prismic to page and show toolbar with changes but changes doe't apply

**Comment by osamaaamer95** [comment]
+1

**Comment by jgcmarins** [comment]
I am experiencing same problem

**Comment by leogilmour** [comment]
And me!

**Comment by Duaner** [comment]
Hey, We just released a new version on npm this is an alpha version at the moment that will introduce changes in the configuration.

Let us know if this fixed the issue. ;)

**Comment by nikita-seliverstov** [comment]
I updated gatsby-source-prismic-graphql to 3.6.2, but it does't fix the issue, console output is 
has been blocked by CORS policy: No 'Access-Control-Allow-Origin'. The URL in prismic preview configuration is correct

**Comment by digeverything** [comment]
> Hey, We just released a new version on npm this is an alpha version at the moment that will introduce changes in the configuration.
> 
> Let us know if this fixed the issue. ;)

I upgraded the package to `gatsby-source-prismic-graphql@3.6.3-alpha.12`.
I'm still not seeing the preview changes for a singleton, I am however seeing the preview changes for a repeatable page.
